### ISSUE TITLE
TreeGrid should support expand/collapse trigger on icon click only

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#1091]
When using a TreeGrid as a normal tree, it is a bit strange that expand/collapse is triggered when clicking on the expand/collapse icon (v, >) **and** the cell's content. So when the user clicks an element in the tree which has children, also expand or collapse occurs.

It would be nice if expand/collapse could be triggered only when clicking on the expand/collapse icon (v, >).
Maybe an option to specify this on TreeGrid level would be a good solution.

**Comment by KiteDX** [comment]
This also has an impact on actual usability. I'm using a one-column TreeGrid as part of a master-detail view (Tree to the left, details area to the right).
If the text of an expandable node in the tree is too long, a normal user basically has no chance of selecting the node itself as all of the area is blocked by the text and the expand/collapse functionality (also see here https://github.com/vaadin/flow-components/issues/1797)

**Comment by web-padawan** [comment]
Workaround: https://github.com/vaadin/flow-components/issues/1684#issuecomment-536564982

**Comment by HerbertsVaadin** [comment]
A more modern CSS workaround:
```css
vaadin-grid vaadin-grid-tree-toggle {
    /* Allow expanding of nodes only by the toggle icon, instead of the whole cell. */
    pointer-events: none;
    &::part(toggle) {
        pointer-events: auto;
    }
}
```
