### ISSUE TITLE
Progress bar hangs when updating large UI

### ISSUE THREAD

**Issue by theshoeshiner** [vaadin/flow-components#4841]
### Description

I have an indeterminate progress bar which tracks a background thread. The background progress updates work fine, but the last operation is pushing a large number of updates to the UI. When this push happens the indeterminate progress bar hangs in place, with the animation stopped. I assume this is because the UI is updating, however this is far from ideal and partially defeats the purpose of an indeterminate progress bar. When the UI update is large this hang can last 3-4 seconds.

### Expected outcome

I would expect an indeterminate progress bar to continue to animate right up until it is removed from the display, with no noticeable pause to the user.

### Minimal reproducible example

```java
ProgressBar pb  = new ProgressBar(0,100);
 pb.setIndeterminate(true);
 add(pb);
 
 Span elements = new Span();
 add(elements);
 
 UI ui = UI.getCurrent();
 
 Button button = new Button("Go", click -> {
  executor.execute(() -> {
   ui.access(() -> {
    for(int i=0;i<10000;i++) {
    	elements.add(new Span(RandomStringUtils.randomAlphabetic(10)));
    }
   });
  });
 });
 add(button);
```

### Steps to reproduce

1. Add Snippet to a view
2. Open page - progress bar is animated
3. Click "Go" button
4. Progress bar is animated for a short time, then hangs as UI updates are pushed/drawn

### Environment

Vaadin version(s): 23
OS: Windows

### Browsers

Chrome, Edge

**Comment by theshoeshiner** [comment]
@rolfsmeds This is not a CSS limitation. I can put another icon on the same page, and animate via CSS, and it has no problems maintaining smooth animation while loading the elements.

You can add the following code to the test and confirm that this is an issue with the progress bar and not CSS in general.

```java
Icon icon = VaadinIcon.COG.create();
    	icon.addClassNames("running");
    	add(icon);
```

```css
vaadin-icon.running {
	animation-name: spin;
  	animation-duration: 5000ms;
  	animation-iteration-count: infinite;
  	animation-timing-function: linear; 
}

@keyframes spin {
    from {
        transform:rotate(0deg);
    }
    to {
        transform:rotate(360deg);
    }
}

```
