### ISSUE TITLE
[Grid] Using compact grid rows leads to error fetching data and blank lines

### ISSUE THREAD

**Issue by kristapsstrals** [vaadin/flow-components#5126]
### Description

I have a need to show a compressed grid so that it can fit more data in one go. This leads to about 22 items in the grid screen (normal grid without CSS has about 10 items). However, this leads to an error:

```log
[qtp1107218767-83] WARN com.vaadin.flow.data.provider.DataCommunicator - Attempted to fetch more items from server than allowed in one go: number of items requested '1300', maximum items allowed '500'.
```
Looking at the gridConnector.js this is because there are a lot more items in the table in one go (~700 vs ~120) and `gridConnector.js` leads to a fetch
```js
fetch(firstPage * grid.pageSize, count * grid.pageSize);
```
of 
```js
fetch(0, 1300)
```

while in a normal scenario, it looks more like `fetch(0, 100)`.

This is really strange, since there are only 10 more items on the screen.

result:
![image](https://github.com/vaadin/flow-components/assets/26419290/5102d32c-af98-4f19-920a-3c0609cfe914)

Replicated using vaadin base-starter-gradle project and vaadin 23.3.13

### Expected outcome

html table does not have 700 elements in it for just 10 additional visible items on screen. There are no errors for trying to fetch more than 500 items from server.
In the regular grid scenario it shows ~10 items on screen and it fetches ~100 items for smooth scrolling.
In the not-working scenario, there are ~20 items on screen and it fetches ~1200 items for smooth scrolling.

That seems like an overkill for just 10 additional items. Even if we request twice as many items, it would be 200, not 1200 items...

### Minimal reproducible example

vaadin-grid.css
```css
[part~="cell"] ::slotted(vaadin-grid-cell-content) {
    display: flex;
    align-items: center;
    font-size: 11px;
    padding: 0;
    height: 100%;
}
```
styles.css
```css
vaadin-grid::part(header-cell) {
    min-height: unset;
}

vaadin-grid::part(body-cell) {
    min-height: unset;
}
```

java:
```java
var list = IntStream.range(0, 3000).boxed()
    .map(i -> "item-" + i).collect(Collectors.toList());
var grid = new Grid<String>();
grid.addColumn(new ComponentRenderer<>(item -> new Span(item)));
grid.setItems(list);
add(grid);
```

### Steps to reproduce

1. create a custom theme, add the `components/vaadin-grid.css` content and `styles.css` content
2. add java code to any vaadin view

### Environment

Vaadin version(s): 
OS: 23.3.13
