### ISSUE TITLE
RichTextEditor: add support for hiding toolbar buttons

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#6298]
### Describe your motivation

I want to severely limit the amount of formatting which the user can input via the toolbar buttons (e.g. I want to hide the code, subscript, superscript, image and link buttons). There looks to be no server-side API in RichTextEditor 23.4.0 to do that.

### Describe the solution you'd like

`setVisibleToolbarButtons(EnumSet<ToolbarButton>)` would be great to have.

**Comment by web-padawan** [comment]
Hiding these buttons is already doable with CSS e.g. using `::part()` selectors like this:

```css
vaadin-rich-text-editor::part(toolbar-group-block),
vaadin-rich-text-editor::part(toolbar-group-rich-text),
vaadin-rich-text-editor::part(toolbar-group-glyph-transformation) {
  display: none;
}
```
